### ISSUE TITLE
Annotatins are not showing even after saving video

### ISSUE THREAD

**Issue by yogiswar1987** [OpenHypervideo/FrameTrail#1]
In demo if drop an annotation and save then go preview, i don't see annotation on the video

**Comment by tammo0** [comment]
@yogiswar1987 
are you editing project 1 hypervideo 7 ("Multiple Users Annotation Example") as user "test"?

Then i can see your annotations.
You just need to click on the annotation below the timeline (see attached image, "2") to open them or enable the "Annotation Preview" Area (see attached image step 1.a and 1.b. -
gearwheel on the right bottom of the page).

![annotations_visible](https://cloud.githubusercontent.com/assets/1723024/14216094/2e3759e2-f847-11e5-9d99-c9be2d2b896d.jpg)

**Comment by OpenHypervideo** [comment]
Thx for the feedback @yogiswar1987 If you want to place contents on top of the video, the way to go would be to use "overlays", instead of annotations. The concept is explained here: http://frametrail.org/tutorials-gettingstarted.html.
