### ISSUE TITLE
No config file found

### ISSUE THREAD

**Issue by mmahrous** [OpenHypervideo/FrameTrail#24]
I tried to install and configure FrameTrail on a server using apache, but when I try to go to /projectmanager an alert appears with "No config file." apparently the _data folder is missing, can any one help me as we need to use it in a youth camp that will have interactive video editing workshop.

**Comment by OpenHypervideo** [comment]
Please make sure you are also running PHP and go to the root directory (not /projectmanager). FrameTrail should just install automatically. If you still experience the problem, make sure the directory is writable by PHP (a workaround is to create an empty "/_data" directory in root and make that writable).
