### ISSUE TITLE
Open a HTML <iframe> in the side panel

### ISSUE THREAD

**Issue by lucasa** [OpenHypervideo/FrameTrail#3]
Hi!

Is possible to render a HTML code like <iframe> as annotation?
I want to implement that, so a embeded page could be rendered in the side panel.

Where in the code I could to implement it?

Lucas

**Comment by OpenHypervideo** [comment]
Depends on what exactly you want to do:
iFrame contents can be rendered by adding a "webpage" resource as an annotation. If you want to show that in the side panel, you just have to activate the annotation preview (which kind of is the side panel).
If you want to add custom HTML, that's currently only possible for overlays. So for annotations, you would need to save an HTML page to the resources folder and manually add it to the resources json file (or just upload it somewhere and add it as a "webpage").

Is that what you meant?

**Comment by lucasa** [comment]
Nice, the embeded html annotation works like a charm!
i'm going to use Frametrail in a education course.
Thanks again.
