### ISSUE TITLE
User not loggin in with Masterpassword

### ISSUE THREAD

**Issue by BaelishLord** [OpenHypervideo/FrameTrail#31]
I have logged in with master password but still shows error as below. How to create and manage users? Please help

![image](https://user-images.githubusercontent.com/21212636/49139438-d2215f80-f317-11e8-9e7b-148e26d4a4af.png)

**Comment by OpenHypervideo** [comment]
Please try and use the develop branch instead:
https://github.com/OpenHypervideo/FrameTrail/archive/develop.zip
The project management has been removed entirely and many fixes have been made, but none of this is yet merged into the master branch. Sorry about the inconvenience and let me know if things work with the develop branch.

**Comment by BaelishLord** [comment]
Hi, i was able to install your developer version but on any action it gets logged out and asks to login again? how to fix that?

**Comment by OpenHypervideo** [comment]
I'm not sure what you mean. Did you delete the old "_data" directory (you need to do that in order to freshly install the develop branch)?
