### ISSUE TITLE
tagdefinitions.json example

### ISSUE THREAD

**Issue by hvkoops** [OpenHypervideo/FrameTrail#32]
Thank you for creating such a nice open-source project. I am confused about tags. I cannot create tags from the GUI, and tagdefinitions.json is currently empty (containing only `{}`). 
Would it be possible to share an example tagdefinitions.json file, or an explanation how to create tags?

**Comment by OpenHypervideo** [comment]
Hi Hendrik, sorry for the late reply.
There is unfortunately not yet a UI for managing tags, so they have to be manually configured / edited in the `tagdefinitions.json` file. As soon as that file includes tag definitions, they can be used when adding / editing annotations (via the "My Annotations" UI), as well as when editing Content Views in the "Layout" section (Type: Content Collection -> "Filter by tags"). Here is an example structure for the tag definitions file:

`{
	"prototype": {
		"en": {
			"label": "Prototype",
			"description": "Lorem English Dolor Sit Amet"
		},
		"de": {
			"label": "Prototyp",
			"description": "Lorem Deutsch Dolor Sit Amet"
		}
	},
	"testtag": {
		"en": {
			"label": "First Test Tag",
			"description": "Lorem English Dolor Sit Amet"
		},
		"de": {
			"label": "Erster Test Tag",
			"description": "Lorem Deutsch Dolor Sit Amet"
		}
	},
	"zweiter_test_tag": {
		"en": {
			"label": "Second Test Tag",
			"description": "Lorem English Dolor Sit Amet"
		},
		"de": {
			"label": "Zweiter Test Tag",
			"description": "Lorem Deutsch Dolor Sit Amet"
		}
	},
	"shortform_tag": {
		"en": {
			"label": "Longform Tag",
			"description": "Lorem English Dolor Sit Amet"
		},
		"de": {
			"label": "Tag Name",
			"description": "Lorem Deutsch Dolor Sit Amet"
		}
	},
	"shortform_test": {
		"en": {
			"label": "Longform Test",
			"description": "Lorem English Dolor Sit Amet"
		},
		"de": {
			"label": "Langer Tag Test",
			"description": "Lorem Deutsch Dolor Sit Amet"
		}
	},
	"tagtest12": {
		"en": {
			"label": "Tagtest",
			"description": "Lorem English Dolor Sit Amet"
		},
		"de": {
			"label": "Tagtest",
			"description": "Lorem Deutsch Dolor Sit Amet"
		}
	}
}`
