### ISSUE TITLE
Project _index.json does not exist

### ISSUE THREAD

**Issue by dwiehoff** [OpenHypervideo/FrameTrail#33]
When creating a project via the UI, this is the error that shows.

**Comment by OpenHypervideo** [comment]
Sorry for the delay. Please try out the latest release, where the "project" concept has been removed entirely: https://github.com/OpenHypervideo/FrameTrail/archive/v0.9.6-beta.zip.
I'm going to close this issue as it's not relevant anymore for the current versions, but please get in touch again if there are any problems.
