### ISSUE TITLE
help request getting FrameTrail going

### ISSUE THREAD

**Issue by iPanini** [OpenHypervideo/FrameTrail#34]
Hi,
Not sure this is the right way to solve this, if not, please let me know. Trying anyway.
I'm running macos Catalina. Have installed xampp. That is running and php info checked.
Document root lives under /opt/lampp/htdocs
I cloned FrameTrail to this location, so it is at /opt/lampp/htdocs/FrameTrail

If I point my browser to http;//ip-of-xampp/FrameTrail/setup.html I get the FrameTrail interface asking me:
1. Admin Mail-address (login-name)
2. Admin Username
3. Admin Password

I can not get any further.
My interpretation is that I need to enter my mail-address, chose my admin-username and my admin-password and proceed from there.

However I only get: "An error occured. Please try again"

How to solve this? Thanks for helping out!

**Comment by OpenHypervideo** [comment]
You've correctly set up everything. Please try setting CHMOD 777 on the FrameTrail directory (all read & write permissions) just to be sure. If that doesn't work, check if your server meets the minimum requirements (esp. the PHP version). The error messages will be more clear about this in the future.

**Comment by iPanini** [comment]
It works now! Thanks! I must have used wrong permissions (think 755)
I've also chown-ed everything to user bitnami as this seems the apache user on xampp.

**Comment by OpenHypervideo** [comment]
Great! Enjoy your FrameTrail journey!
