### ISSUE TITLE
probleme to installation

### ISSUE THREAD

**Issue by teveka** [OpenHypervideo/FrameTrail#40]
this installation no create user
can you  help my

thanks

[Wed Jan 25 11:47:29.499756 2023] [proxy_fcgi:error] [pid 1289] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /var/www/FrameTrail/_server/user.php:368\nStack trace:\n#0 /var/www/FrameTrail/_server/user.php(368): in_array()\n#1 /var/www/FrameTrail/_server/user.php(88): getUserColors()\n#2 /var/www/FrameTrail/_server/ajaxServer.php(301): userRegister()\n#3 {main}\n thrown in /var/www/FrameTrail/_server/user.php on line 368',

**Comment by tammo0** [comment]
Hi!
Closed because it should be fixed now.
Feel free to re open it if the problem still exists.
