### ISSUE TITLE
Unable to install, create admin user -> PHP 8.1 error

### ISSUE THREAD

**Issue by gaborkukucska** [OpenHypervideo/FrameTrail#41]
Hello :)

Would love to evaluate this awesome looking software of yours but I got stuck during install. I'm trying to run it on a php8.1 Nginx Ubuntu server but I get a PHP error:

2023/02/20 02:41:02 [error] 17922#17922: *39 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /var/www/FrameTrail/_server/user.php:368
Stack trace:
#0 /var/www/FrameTrail/_server/user.php(368): in_array()
#1 /var/www/FrameTrail/_server/user.php(88): getUserColors()
#2 /var/www/FrameTrail/_server/ajaxServer.php(301): userRegister()
#3 {main}
  thrown in /var/www/FrameTrail/_server/user.php on line 368" while reading response header from upstream, client: 49.194.166.223, server: video.mediatoken.link, request: "POST /_server/ajaxServer.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "##########", referrer: "https://##########/setup.html"

Any help would be appreciated.
Thanks!!

**Comment by tammo0** [comment]
Hi @gaborkukucska 
Please try it now with a clean clone, so there are no broken installation files left.
Greetings!

**Comment by gaborkukucska** [comment]
Great work @tammo0 ! This was the quickes response I ever got on github :)
this has worked, I managed to get it innitiated and start testing and I have more errors for you :)
